// variable labels 2001–2019

lab var bc_correlat "Identificador del hogar"
lab var bc_nper "Identificador de la persona"
lab var bc_filtloc "Identificador del tipo de localidad"
lab var bc_pesoan "Expansor del año"
lab var bc_mes "Mes en que se realizó la entrevista"
lab var bc_anio "Año en que se realizó la entrevista"
lab var bc_dpto "Departamento de residencia"
lab var bc_ccz "Centros Comunales Zonales de Montevideo"
lab var bc_area "Área de residencia"
lab var bc_pe2 "Sexo "
lab var bc_pe3 "Edad"
lab var bc_pe4 "Relación de parentesco"
lab var bc_pe5 "Estado civil"
lab var bc_pe6a "Derecho de atención médica (a)"
lab var bc_pe6b "Derecho de atención médica (b)"
lab var bc_pe6a1 "Cómo recibe el derecho"
lab var bc_pe11 "Asistencia actual a centro educativo"
lab var bc_pe12 "Asistió a centro educativo"
lab var bc_pe13 "Asistencia actual público o privado"
lab var bc_edu "Años de educación aprobados"
lab var bc_edu_1 "Años de educación aprobados"
lab var bc_finalizo "Finaliza máximo nivel "
lab var bc_pobp "Condición de actividad"
lab var bc_pf41 "Categoría de ocupación (a)"
lab var bc_cat2 "Categoría de ocupación (b)"
lab var bc_pf081 "Tamaño del establecimiento"
lab var bc_pf082 "Tamaño del establecimiento por tramos"
lab var bc_pf40 "Rama del establecimiento"
lab var bc_rama "Rama de actividad a un dígito"
lab var bc_pf39 "Tipo de ocupación"
lab var bc_tipo_ocup "Tipo de ocupación principal"
lab var bc_pf07 "Cantidad de empleos"
lab var bc_pf051 "Horas trabajadas en ocupación principal la semana pasada"
lab var bc_pf052 "Horas trabajadas en otras ocupaciones la semana pasada"
lab var bc_pf053 "Horas totales trabajadas la semana pasada"
lab var bc_pf06 "Horas totales trabajadas habitualmente en la semana"
lab var bc_horas_sp "Horas trabajadas la semana pasada "
lab var bc_horas_sp_1 "Horas trabajadas la semana pasada en ocupación principal"
lab var bc_horas_hab "Horas trabajadas habitualmente en la semana "
lab var bc_horas_hab_1 "Horas trabajadas en ocupación principal"
lab var bc_pf04 "Motivo por el que no trabaja"
lab var bc_pf21 "Busco trabajo la semana pasada"
lab var bc_pf22 "Causa por las que no buscó trabajo"
lab var bc_pf26 "Semanas de búsqueda de trabajo"
lab var bc_pf34 "Causas por las que dejó el último trabajo"
lab var bc_reg_disse "Cobertura médica por disse o fonasa"
lab var bc_register "Cobertura de seguridad social en ocupación principal"
lab var bc_register2 "Cobertura de seguridad social en trabajo "
lab var bc_subocupado "Trabaja menos horas de las que desearía"
lab var bc_subocupado1 "Trabaja menos horas de las que desearía"
lab var bc_pg11p "Sueldos privados principal"
lab var bc_pg12p "Comisiones privados principal"
lab var bc_pg13p "Beneficios Sociales privados principal"
lab var bc_pg14p "Aguinaldo privados principal"
lab var bc_pg15p "Salario vacacional privados principal"
lab var bc_pg16p "Propina/gratificaciones privados principal"
lab var bc_pg17p "En especie privados principal"
lab var bc_pg11o "Sueldos privados otras ocupaciones"
lab var bc_pg12o "Comisiones privados otras ocupaciones"
lab var bc_pg13o "Beneficios Sociales privados otras ocupaciones"
lab var bc_pg14o "Aguinaldo privados otras ocupaciones"
lab var bc_pg15o "Salario vacacional privados otras ocupaciones"
lab var bc_pg16o "Propina/gratificaciones privados otras ocupaciones"
lab var bc_pg17o "En especie privados otras ocupaciones"
lab var bc_pg21p "Sueldos público principal"
lab var bc_pg22p "Comisiones público principal"
lab var bc_pg23p "Beneficios Sociales público principal"
lab var bc_pg24p "Aguinaldo público principal"
lab var bc_pg25p "Salario vacacional público principal"
lab var bc_pg26p "Propina/gratificaciones público principal"
lab var bc_pg27p "En especie público principal"
lab var bc_pg21o "Sueldos público otras ocupaciones"
lab var bc_pg22o "Comisiones público otras ocupaciones"
lab var bc_pg23o "Beneficios Sociales público otras ocupaciones"
lab var bc_pg24o "Aguinaldo público otras ocupaciones"
lab var bc_pg25o "Salario vacacional público otras ocupaciones"
lab var bc_pg26o "Propina/gratificaciones público otras ocupaciones"
lab var bc_pg27o "En especie público otras ocupaciones"
lab var bc_pg11t "Sueldos otras ocupaciones"
lab var bc_pg12t "Comisiones otras ocupaciones"
lab var bc_pg13t "Beneficios Sociales otras ocupaciones"
lab var bc_pg14t "Aguinaldo otras ocupaciones"
lab var bc_pg15t "Salario vacacional otras ocupaciones"
lab var bc_pg16t "Propina/gratificaciones otras ocupaciones"
lab var bc_pg17t "En especies otras ocupaciones"
lab var bc_pg31p "Dinero cp sl principal"
lab var bc_pg32p "Asignaciones cp sl principal"
lab var bc_pg33p "Especie cp sl principal"
lab var bc_pg31o "Dinero cp sl otras ocupaciones"
lab var bc_pg32o "Asignaciones cp sl otras ocupaciones"
lab var bc_pg33o "Especie cp sl otras ocupaciones"
lab var bc_pg41p "Dinero cp cl principal"
lab var bc_pg42p "Asignaciones cp cl principal"
lab var bc_pg43p "Especie cp cl principal"
lab var bc_pg41o "Dinero cp cl otras ocupaciones"
lab var bc_pg42o "Asignaciones cp cl otras ocupaciones"
lab var bc_pg43o "Especie cp cl otras ocupaciones"
lab var bc_pg51p "Dinero patrón principal"
lab var bc_pg52p "Especie patrón principal"
lab var bc_pg51o "Dinero patrón otras ocupaciones"
lab var bc_pg52o "Especie patrón otras ocupaciones"
lab var bc_pg71p "Dinero coop principal"
lab var bc_pg72p "Asignaciones coop principal"
lab var bc_pg73p "Especie coop principal"
lab var bc_pg71o "Dinero coop otras ocupaciones"
lab var bc_pg72o "Asignaciones coop otras ocupaciones"
lab var bc_pg73o "Especie coop otras ocupaciones"
lab var bc_pg60p "Utilidades totales patrones principal"
lab var bc_pg60p_cpcl "Utilidades totales cp cl principal"
lab var bc_pg60p_cpsl "Utilidades totales cp sl principal"
lab var bc_pg60o "Utilidades totales patrones otras ocupaciones"
lab var bc_pg60o_cpcl "Utilidades totales cp cl otras ocupaciones"
lab var bc_pg60o_cpsl "Utilidades totales cp sl otras ocupaciones"
lab var bc_pg80p "Utilidades totales coop principal"
lab var bc_pg80o "Utilidades totales coop otras ocupaciones"
lab var bc_pg121 "Alquiler"
lab var bc_pg122 "Alquiler (exterior)"
lab var bc_pg131 "Intereses"
lab var bc_pg132 "Intereses (exterior)"
lab var bc_otras_utilidades "Otras utilidades imputables al hogar"
lab var bc_ot_utilidades "Otras utilidades imputables al hogar"
lab var bc_otras_capital "Medianería, pastoreo y ganado a capitalizar a nivel de hogar"
lab var bc_otros_lab "Otros ingresos laborales"
lab var bc_otros_benef "Beneficios sociales"
lab var bc_pag_at "Pagos atrasados"
lab var bc_pg91 "Jubilaciones o pensiones"
lab var bc_pg92 "Jubilaciones o pensiones del exterior"
lab var bc_pg911 "Jubilaciones"
lab var bc_pg912 "Pensiones"
lab var bc_pg921 "Jubilaciones del exterior"
lab var bc_pg922 "Pensiones del exterior"
lab var bc_pg101 "Becas o subsidio"
lab var bc_pg102 "Becas o subsidio del exterior"
lab var bc_pg111 "Contribuciones"
lab var bc_pg112 "Contribuciones del exterior"
lab var bc_pa11 "Ingreso agropecuario 11"
lab var bc_pa12 "Ingreso agropecuario 12"
lab var bc_pa13 "Ingreso agropecuario 13"
lab var bc_pa21 "Ingreso agropecuario 21"
lab var bc_pa22 "Ingreso agropecuario 22"
lab var bc_pa31 "Ingreso agropecuario 31"
lab var bc_pa32 "Ingreso agropecuario 32"
lab var bc_pa33 "Ingreso agropecuario 33"
lab var bc_pg191 "Otros ingresos 191"
lab var bc_pg192 "Otros ingresos 192"
lab var bc_afam "Asignaciones familiares"
lab var afam_pe "Asignaciones familiares-Plan de equidad"
lab var afam_cont "Asignaciones familiares-Contributivas"
lab var afam_pe_hog "Asignaciones familiares-Plan de equidad a nivel de hogar"
lab var afam_cont_hog "Asignaciones familiares-Contributivas a nivel de hogar"
lab var monto_afam_pe "Monto imputado de AFAM-PE"
lab var monto_afam_cont "Monto imputado de AFAM-Contributivas"
lab var bc_yciudada "Ingreso ciudadano"
lab var bc_yalimpan "Tarjeta alimentaria"
lab var bc_yhog "Ingreso del hogar"
lab var bc_pg14 "Valor locativo"
lab var bc_as_privados "Ingresos de la ocupación principal de asalariados privados"
lab var bc_as_publicos "Ingresos de la ocupación principal de asalariados públicos"
lab var bc_as_otros "Ingresos totales privados y públicos de otras ocupaciones"
lab var bc_asalariados "Ingresos totales asalariados todas ocupaciones"
lab var bc_as_agropec "Ingresos totales asalariados agropecuarios"
lab var bc_patrones "Ingresos de todas las ocupaciones de los patrones"
lab var bc_pat_agropec "Ingresos totales patrones agropecuarios"
lab var bc_cpropiasl "Ingresos de todas las ocupaciones de los cpropia sin local"
lab var bc_cpropiacl "Ingresos de todas las ocupaciones de los cpropia con local"
lab var bc_cp_agropec "Ingresos totales cuenta propia agropecuarios"
lab var bc_cooperat "Ingresos de todas las ocupaciones de los cooperativas"
lab var bc_ot_agropec "Ingresos totales otros agropecuarios"
lab var bc_principal "Ingresos laborales de la ocupación principal (solo asalariados)"
lab var bc_ing_lab "Todos los ingresos laborales de todas las ocupaciones para todos los ocupados"
lab var bc_utilidades "Ingresos totales por utilidades"
lab var bc_alq "Ingresos totales por alquileres"
lab var bc_intereses "Ingresos totales por intereses"
lab var bc_ut_agropec "Ingresos totales por utilidades agropecuarias"
lab var bc_ing_cap "Ingresos del capital (utilidades, alquileres, intereses)"
lab var bc_jub_pen "Ingresos por jubilaciones y pensiones"
lab var bc_jub_pene "Ingresos por jubilaciones y pensiones del exterior"
lab var bc_tarjeta "Ingreso por tarjeta alimentaria"
lab var bc_bs_sociales "Ingresos por transferencias sociales"
lab var bc_transf_hog "Ingresos totales por transferencias al hogar"
lab var bc_beneficios "Ingresos por beneficios y transferencias sociales"
lab var bc_ipc "IPC para montevideo a diciembre 2006"
lab var bc_ipc_nuevo "IPC para montevideo y el interior a diciembre 2010"
lab var bc_ipc_tot "IPC total país"
lab var bc_cuotmilit "Cuotas militares"
lab var bc_cuotabps "Cuota pagada por DISSE, BPS o similar jubilado o pensionista"
lab var bc_disse_p "Cuota pagada por DISSE, BPS o similar en ocupación principal"
lab var bc_disse_o "Cuota pagada por DISSE, BPS o similar en otras ocupaciones"
lab var bc_disse "Cuota pagada por DISSE, BPS o similar en seguro de paro"
lab var bc_ht11_sss "Ingreso del hogar por todo concepto (con val loc) sin seguro de salud"
lab var bc_salud "Ingresos por seguro de salud imputados al hogar"
lab var bc_ht11_css "Ingreso del hogar por todo concepto (con val loc) con seguro de salud"
lab var bc_percap_iecon "Ingreso per cápita del hogar con bc_ht11_sss"
